"""suppression des champs 'nom', 'prenom', 'taille', 'sexe', 'sport_licence', 'region', 'nationalité_francaise','date_creation_compte', 'orientation_sexuelle'

Revision ID: 5ab752d290d5
Revises: 
Create Date: 2025-07-23 17:56:10.209621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ab752d290d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'prenom')
    op.drop_column('clients', 'date_creation_compte')
    op.drop_column('clients', 'nom')
    op.add_column('clients_meta', sa.Column('nb_enfants', sa.Integer(), nullable=True))
    op.add_column('clients_meta', sa.Column('quotient_caf', sa.Float(), nullable=True))
    op.drop_column('clients_meta', 'sexe')
    op.drop_column('clients_meta', 'sport_licence')
    op.drop_column('clients_meta', 'region')
    op.drop_column('clients_meta', 'taille')
    op.drop_column('clients_meta', 'nationalite_francaise')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients_meta', sa.Column('nationalite_francaise', sa.BOOLEAN(), nullable=True))
    op.add_column('clients_meta', sa.Column('taille', sa.FLOAT(), nullable=True))
    op.add_column('clients_meta', sa.Column('region', sa.VARCHAR(), nullable=True))
    op.add_column('clients_meta', sa.Column('sport_licence', sa.BOOLEAN(), nullable=True))
    op.add_column('clients_meta', sa.Column('sexe', sa.VARCHAR(length=1), nullable=True))
    op.drop_column('clients_meta', 'quotient_caf')
    op.drop_column('clients_meta', 'nb_enfants')
    op.add_column('clients', sa.Column('nom', sa.VARCHAR(), nullable=True))
    op.add_column('clients', sa.Column('date_creation_compte', sa.DATE(), nullable=True))
    op.add_column('clients', sa.Column('prenom', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
