"""suppression des champs 'historique_credits', 'score_credit'

Revision ID: b153280738ca
Revises: 5ab752d290d5
Create Date: 2025-07-23 18:33:14.295044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b153280738ca'
down_revision: Union[str, Sequence[str], None] = '5ab752d290d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients_situation', 'score_credit')
    op.drop_column('clients_situation', 'historique_credits')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients_situation', sa.Column('historique_credits', sa.FLOAT(), nullable=True))
    op.add_column('clients_situation', sa.Column('score_credit', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
